name = "Queeronautics"
author = "Illina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8426c62266a2dda7665472acb2ad969bdf4f2bc8aade87ad40f29cbd1c46728e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
