name = "Queeronautics"
author = "Illina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf4143390a4e23584b4316aca6d55f09fff638d917af425c88200003c69cabb1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
