name = "Queeronautics"
author = "Illina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d88ab108fe8c62f4d996a0126e37057d12e26b688c5fbcfe04fb9a6a57158ecf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
